import { getDb } from "../api/queries/connection";
import { categories, watches } from "./schema";

async function seed() {
  console.log("Seeding database...");
  const db = getDb();

  // Seed categories
  await db.insert(categories).values([
    { name: "Diver", slug: "diver", description: "Professional diving watches engineered for extreme depths" },
    { name: "Chronograph", slug: "chronograph", description: "Precision timekeeping with stopwatch complications" },
    { name: "Dress", slug: "dress", description: "Elegant timepieces for formal occasions" },
    { name: "Pilot", slug: "pilot", description: "Aviation-inspired instruments for the skies" },
    { name: "GMT", slug: "gmt", description: "Dual-timezone watches for world travelers" },
  ]);
  console.log("Categories seeded");

  // Seed watches
  await db.insert(watches).values([
    {
      name: "Abyss Deep Diver",
      slug: "abyss-deep-diver",
      description: "A professional-grade diving watch capable of withstanding depths up to 300 meters. Features a unidirectional rotating bezel, luminous markers, and a helium escape valve.",
      price: "4850.00",
      image: "/images/watch-diver.jpg",
      categoryId: 1,
      caseMaterial: "316L Stainless Steel",
      caseSize: "42mm",
      movement: "Automatic Caliber 9001",
      waterResistance: "300m",
      caliber: "CH-9001",
      dialColor: "Deep Blue",
      strapMaterial: "Stainless Steel Bracelet",
      featured: 1,
      inStock: 1,
    },
    {
      name: "Speed Master Chronograph",
      slug: "speed-master-chronograph",
      description: "A tribute to motorsport precision. This chronograph features a tachymeter scale, column-wheel mechanism, and flyback function for split-second timing.",
      price: "7200.00",
      image: "/images/watch-chrono.jpg",
      categoryId: 2,
      caseMaterial: "904L Stainless Steel & 18K Rose Gold",
      caseSize: "40mm",
      movement: "Automatic Chronograph CH-7750",
      waterResistance: "100m",
      caliber: "CH-7750",
      dialColor: "Midnight Black",
      strapMaterial: "Alligator Leather",
      featured: 1,
      inStock: 1,
    },
    {
      name: "Heritage Dress Classic",
      slug: "heritage-dress-classic",
      description: "Understated elegance meets mechanical excellence. The ultra-thin case houses a hand-wound movement visible through a sapphire display back.",
      price: "3600.00",
      image: "/images/watch-dress.jpg",
      categoryId: 3,
      caseMaterial: "18K Rose Gold",
      caseSize: "38mm",
      movement: "Manual Wind CH-6497",
      waterResistance: "30m",
      caliber: "CH-6497",
      dialColor: "Silver White",
      strapMaterial: "Genuine Leather",
      featured: 1,
      inStock: 1,
    },
    {
      name: "Aviator Pro Pilot",
      slug: "aviator-pro-pilot",
      description: "Inspired by cockpit instruments, this pilot watch features large luminous Arabic numerals, anti-magnetic shielding, and an extended power reserve for long flights.",
      price: "4200.00",
      image: "/images/watch-pilot.jpg",
      categoryId: 4,
      caseMaterial: "Titanium Grade 5",
      caseSize: "44mm",
      movement: "Automatic Caliber 2892-A2",
      waterResistance: "100m",
      caliber: "CH-2892",
      dialColor: "Matte Black",
      strapMaterial: "Canvas Military Strap",
      featured: 1,
      inStock: 1,
    },
    {
      name: "Meridian GMT Master",
      slug: "meridian-gmt-master",
      description: "Track two time zones simultaneously with the independent GMT hand. The bi-color ceramic bezel represents day and night at a glance.",
      price: "5800.00",
      image: "/images/watch-gmt.jpg",
      categoryId: 5,
      caseMaterial: "904L Stainless Steel",
      caseSize: "40mm",
      movement: "Automatic GMT CH-3285",
      waterResistance: "200m",
      caliber: "CH-3285",
      dialColor: "Black",
      strapMaterial: "Oyster Bracelet",
      featured: 1,
      inStock: 1,
    },
    {
      name: "Oceanic Elite Diver",
      slug: "oceanic-elite-diver",
      description: "A limited edition diver with a meteorite dial and ceramic bezel. Each piece is individually numbered and tested to 600 meters.",
      price: "12500.00",
      salePrice: "9800.00",
      image: "/images/watch-dial-1.jpg",
      categoryId: 1,
      caseMaterial: "Titanium & Ceramic",
      caseSize: "43mm",
      movement: "Automatic Caliber 3235",
      waterResistance: "600m",
      caliber: "CH-3235-LE",
      dialColor: "Meteorite Grey",
      strapMaterial: "Rubber Dive Strap",
      featured: 1,
      inStock: 1,
    },
    {
      name: "Regal Chronograph Limited",
      slug: "regal-chronograph-limited",
      description: "A numbered limited edition celebrating 50 years of chronograph excellence. Features a column wheel, vertical clutch, and exhibition caseback.",
      price: "9500.00",
      image: "/images/watch-crown.jpg",
      categoryId: 2,
      caseMaterial: "Platinum 950",
      caseSize: "41mm",
      movement: "Automatic Chronograph CH-4130",
      waterResistance: "50m",
      caliber: "CH-4130-LE",
      dialColor: "Ice Blue",
      strapMaterial: "Platinum Bracelet",
      featured: 0,
      inStock: 1,
    },
    {
      name: "Nebula Tourbillon",
      slug: "nebula-tourbillon",
      description: "The pinnacle of haute horlogerie. An open-worked tourbillon movement with a 120-hour power reserve, finished entirely by hand.",
      price: "45000.00",
      image: "/images/watch-blueprint.jpg",
      categoryId: 3,
      caseMaterial: "18K White Gold",
      caseSize: "42mm",
      movement: "Manual Tourbillon CH-TO1",
      waterResistance: "30m",
      caliber: "CH-TO1",
      dialColor: "Skeleton",
      strapMaterial: "Hand-stitched Alligator",
      featured: 0,
      inStock: 1,
    },
  ]);
  console.log("Watches seeded");

  console.log("Seed complete!");
}

seed().catch(console.error);
